In [1]:
import pandas as pd
import joblib
import os

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

In [2]:
import pandas as pd

df = pd.read_csv("../dataset/Student_Performance.csv")

df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [3]:
df["Extracurricular Activities"] = df["Extracurricular Activities"].map({
    "Yes": 1,
    "No": 0
})

df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0

In [4]:
X = df.drop("Performance Index", axis=1)
y = df["Performance Index"]

print(X.head())
print(y.head())

   Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0              7               99                           1            9
1              4               82                           0            4
2              8               51                           1            7
3              5               52                           1            5
4              7               75                           0            8

   Sample Question Papers Practiced
0                                 1
1                                 2
2                                 2
3                                 2
4                                 5
0    91.0
1    65.0
2    45.0
3    36.0
4    66.0
Name: Performance Index, dtype: float64

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(8000, 5)
(2000, 5)

In [6]:
model = RandomForestRegressor(
    n_estimators=20,
    random_state=42
)

model.fit(X_train, y_train)

print("Model Trained Successfully!")

Model Trained Successfully!

In [7]:
predictions = model.predict(X_test)

print(predictions[:10])

[55.7        21.71666667 46.05       29.93333333 42.65       60.15
 47.         85.625      35.7        72.2       ]

In [8]:
print("R2 Score:", r2_score(y_test, predictions))
print("MAE:", mean_absolute_error(y_test, predictions))

R2 Score: 0.9855378486989469
MAE: 1.8487851587301587

In [9]:
os.makedirs("../models", exist_ok=True)

joblib.dump(model, "../models/student_model.pkl", compress=9)

['../models/student_model.pkl']